import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram,
AiFillLinkedin,
AiFillGithub} from 'react-icons/ai';

import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Aristotle Buenaventura Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white  px-10 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex  justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Aristotle</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium dark:text-teal-300'>Aristotle Buenaventura</h2>
            <h3 className='text-2xl py-2 dark:text-white'>Junior Web Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 max-w-xl mx-auto dark:text-white'>"I have a strong foundation in HTML, Tailwind, ReactJs, Laravel, and MySQL, and I'm eager to keep expanding my knowledge and expertise in these areas. I'm also keen to learn new technologies and programming languages, and I'm confident in my ability to adapt quickly to new environments and challenges. I'm passionate about creating user-friendly, aesthetically pleasing websites."</p>
          </div>
          <div className='text-5xl flex justify-center  gap-16 py-3 text-gray-600 dark:text-gray-300 '>
            <AiFillInstagram/>
            <AiFillLinkedin/>
            <AiFillGithub/>
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>

        </section>

        <section>
          <div className='container'>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
               Here's a sneek peek of my work
            </p>
          </div>
          <div className='lg:flex justify-center gap-5'>
            <div>
              <div className='text-center shadow-lg p-10 rounded mb-10 dark:text-white'>
                <Image className='mx-auto pb-5' src={design} height={100} width={100}/>
                <h3 className='font-bold '>Beautiful Design</h3>
                <p>
                  Creating elegant design suited for your design theory
                </p>
              </div>
            </div>
            <div>
              <div className='text-center shadow-lg p-10 rounded mb-10 dark:text-white'>
                <Image className='mx-auto pb-5' src={code} height={100} width={100}/>
                <h3 className='font-bold'>Beautiful Design</h3>
                <p>
                  Creating elegant design suited for your design theory
                </p>
              </div>
            </div>
            <div>
              <div className='text-center shadow-lg p-10 rounded dark:text-white'>
                <Image className='mx-auto pb-5' src={consulting} height={100} width={100}/>
                <h3 className='font-bold'>Beautiful Design</h3>
                <p>
                  Creating elegant design suited for your design theory
                </p>
              </div>
            </div>
          </div>
          <div className='gap-10 mt-5 py-10 grid grid-cols-1 lg:grid-cols-3 md:grid-cols-2'>
              <div className=''>
                <Image src={web1} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
              <div className='basis-1/4 flex-1'>
                <Image src={web2} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
              <div className=''>
                <Image src={web3} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
              <div className=''>
                <Image src={web4} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
              <div className=''>
                <Image src={web5} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
              <div className=''>
                <Image src={web6} classname='rounded-lg object-cover' width={"100%"} height={"100%"} layout="responsive"/>
              </div>
          </div>
        </section>
      </main>
    </div>
  );
}
